### PR TITLE
Fixes #190: Avoid exporting Buffer to dist files.

### LINKED ISSUE #190: Remove unneeded external dependencies
There are a number of libraries and adapters which are loaded by Kinto that will never be used in some circumstances. E.g. polyfills such as isomorphic fetch are not required where a real fetch implementation exists, kinto.js running as privileged JS will not need IDB or local storage adapters.

Can we re-work so such dependencies are injected in, allowing separate distributed scripts to be prepared for different intended uses?

### PR DESCRIPTION
**Pull request by n1k0**
Refs #190. We should get rid of `deep-eql` which carries a dependency to `Buffer` we can't exclude from dist files; we should switch to using nodejs' own `assert#deepEqual` which doesn't have such heavy dependencies.

### CODE REVIEW

**Comment by n1k0** [comment]
>  1,355 additions, 2,465 deletions not shown 

That's much better. r=? @mozmark

**Comment by mozmark** [comment]
This looks good so far - I'm going to do some tests on using this in Firefox to ensure the assert library works there (no reason I can see that it shouldn't).

**Comment by n1k0** [comment]
@mozmark ping, could you please confirm at patch works for you so I can land this?

**Comment by mozmark** [comment]
I can confirm this works (my apologies for delaying you).

r=me

**Pull request merged**
