### PR TITLE
Compute SRIs from npmcdn and add version to table

### PR DESCRIPTION
**Pull request by glasserc**
Since the version of the webpacked assets is not reproducible, use curl to fetch the version of the asset from npmcdn and use that to compute the SRI. Also, add a note in the header of the table to show what version the SRIs correspond to.

r? @Natim @n1k0 @elelay

### CODE REVIEW

**Comment by Natim** [comment]
gg :) r+

**Comment by n1k0** [comment]
Woah, TIL about `npm view`. Smart script =) At some point we may want to move these long commands to separated bash scripts maybe.

r+

**Comment by elelay** [comment]
sweet!

**Comment by leplatrem** [comment]
So, we trust npmcdn then! ;)

**Pull request merged**
