### PR TITLE
Add Kinto master as a TravisCI target (fixes #334)

### LINKED ISSUE #334: Pin Kinto version to use in travis, add Kinto master as secondary target
This has been done for kinto-client already.

### PR DESCRIPTION
**Pull request by leplatrem**
@n1k0 r?

### CODE REVIEW

**Comment by n1k0** [comment]
Only on master... Also has 2000ms timeouts with master.

**Comment by leplatrem** [comment]
> 2000ms timeouts

Failing tests or slow server startup ?

**Comment by n1k0** [comment]
That's much probably slow server startup. I thought setting the higher scope global timeout to `0` (no limit) would affect children tests as well, but it's visibly not. It never fails that way on my box, so hard to investigate.

I can dump the server logs on such a failure though, which would possibly help if anything went wrong with the server itself during startup.

**Comment by n1k0** [comment]
Re a8a2a8af7fe8b4b679c73e12e85df035527ab0d1, does this specifically solves the issues we had with 403, or is this just cosmetics for Kinto master compat?

**Comment by leplatrem** [comment]
It solves a breaking change of kinto master (2.0) where the `default` bucket is not enabled by default.

**Comment by n1k0** [comment]
> It solves a breaking change of kinto master (2.0) where the default bucket is not enabled by default.

Ok. Meaning Kinto.js should probably issue its creation when such configuration is detected, right?

**Comment by leplatrem** [comment]
> Ok. Meaning Kinto.js should probably issue its creation when such configuration is detected, right?

I don't think we should automatize too much. Sometimes we'll be behind a CDN where things can't be created etc.

I'd rather document how to use the underlying `api` object to create bucket or collections.

**Comment by n1k0** [comment]
> I'd rather document how to use the underlying api object to create bucket or collections.

Yeah, that would work. I'm concerned with this is slightly defeating the pure offline-first approach I wanted to have with this project, where you create buckets/collection locally and then synchronize these when back online. Though it's probably okay to require connectivity when performing these operations, I guess.

**Pull request merged**
