### PR TITLE
[WIP] Conversion to TypeScript project

### PR DESCRIPTION
**Pull request by lgleim**
This is a WIP proposal to migrating all sources over to typescript. Your feedback is needed! 

Things done so far:
- Initial conversion of all source files except index.js. Interfaces still lacking documentation & many things are any typed
- ~~Added tsify to browserify build steps~~
- Requires Typescript 2.1 for object spread support
- ~~Dev build works while other builds currently fail due to uglify lacking typescript support. Feedback needed - is it possible to apply uglify to the output of e.g. the dev build?~~
- Switched to `tsc` preprocessing compilation approach. All builds work, some tests still fail.

### CODE REVIEW

**Comment by n1k0** [comment]
We've been actively using [flow](http://flowtype.org) instead of TypeScript in other Kinto-related projects (like the [admin](https://github.com/Kinto/kinto-admin)) with great success, and we don't really want to use two different type systems and keep consistent across the ecosystem.

I should have addressed this concern earlier, sorry for that :/

**Comment by pcleau** [comment]
Hi,
I am about to start an offline first Angular 2 mobile app. I am new in Angular2 and I would very much like to use Kinto.js   (vs. Pouchdb)

@lgleim: I see your huge WIP at https://github.com/lgleim/kinto.js.d.ts

Please, do you know when you expect to release a full reliable typescript Interface for Kintojs ?

Thanks in advance

**Comment by lgleim** [comment]
I deprecated development after the core team decided not to adapt typescript support. I am currently using PouchDB instead of Kinto.js with Angular2. 
My fork at https://github.com/lgleim/kinto.js is however basically a full port of Kinto.js to Typescript. Feel free to fork it and pull in the changes from master. You should be up and running in no time ;)

**Comment by pcleau** [comment]
Thanks for your answer.
Sorry to learn the deprecation.

@lgleim: Please, Should I use your fork at https://github.com/lgleim/kinto.js in production, with Angular2?
Indeed, until then, I exclude PouchDb/couchDb because my offline-first has private  (User)  data and shared data (Team). Kinto.js seems a powerful solution due to its permission model whereas couchdb needs sync between user's DB and global DB.
With Angular2 app, does it mean I should prefer pouchDb/couchDb in production?

Thanks in advance

**Comment by lgleim** [comment]
I would not recommend to use anything deprecated in production, let alone start development based on it unless you take on the burden of maintaining it yourself. You can still use kinto.js without proper typings. The ones I generated at https://github.com/lgleim/kinto.js.d.ts should do you a solid for the moment but you will have to update things when kinto.js makes api changes. Good luck with your project ;)

**Comment by pcleau** [comment]
Many thanks for your answers and your time.
Have a good week ;)

**Pull request closed without merging**
