### PR TITLE
[WIP] feature: deleteAll records (fix #556)

### LINKED ISSUE #556: Add deleteAll() method on collection
The available `clear()` method would wipeout the local data but won't delete records remotely.

We would need a method to delete all records locally and delete records remotely on sync...

This method on the collection class would set the «sync status» of its records to `deleted`, as if they would have been individually deleted with `deleteRecord()`
https://github.com/Kinto/kinto.js/blob/833a879b3aecd6c0abc407499eff29358b35a078/src/collection.js#L604

A test should be added here:
https://github.com/Kinto/kinto.js/blob/833a879b3aecd6c0abc407499eff29358b35a078/test/collection_test.js#L1169
That:
- creates some records in setup
- calls the new `deleteAll()`
- verifies that every records are still here but marked as `deleted` (ie. virtually deleted) using something like:
```js
articles.list(
            { filters: { _status: "deleted" } },
            { includeDeleted: true }
);
```

I think we may also want to check that the `deleteAll()` method emits an event.

### PR DESCRIPTION
**Pull request by enguerran**
- [X] add test
- [ ] pass the test
- [ ] refactor

### CODE REVIEW

**Comment by n1k0** [comment]
What's the difference with `clear()`?

**Comment by leplatrem** [comment]
`clear()` would wipe everything out locally. `deleteAll()` would replicate the deletions remotely.

**Comment by enguerran** [comment]
It is linked to #556

`clear()` deletes the whole local database and wait for a `sync()` to repopulate it.

`deleteAll()` marks every records as `mark_as_deleted` and wait for a `sync()` to deleteAll on the server.

**Comment by n1k0** [comment]
Ok, makes sense.

**Pull request closed without merging**
