### PR TITLE
fetchChangesSince should not throw if an empty 200 response is rece…

### PR DESCRIPTION
**Pull request by ferjm**
…ived

### CODE REVIEW

**Comment by ferjm** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1214661

**Comment by n1k0** [comment]
Tthe patch looks good, though I'm puzzled as how this could ever happen (empty 200 response on fetch). Hints? @Natim @leplatrem @ametaireau

**Comment by Natim** [comment]
@n1k0 this is related to #209

When the server was flushed, you can end-up with a 200 and an empty response with If-None-Match header.

Also it might be possible to get that with Syncto I guess.

**Comment by n1k0** [comment]
> When the server was flushed, you can end-up with a 200 and an empty response

You mean no JSON *at all*? That sounds like a bug to me. Shouldn't a 200 should always return a JSON body?

**Comment by Natim** [comment]
> You mean no JSON at all?

No it will be a ``{"data": []}`` @ferjm I would be interested in having the query that leads to this response. As @n1k0 said it is probably a bug.

**Comment by n1k0** [comment]
So what's the status of this? Is it a server bug, or should we expect possibly empty 200 responses from the server?

**Comment by leplatrem** [comment]
In the Kinto protocol, on the list of records, we will never return an empty dict with a 200 response.

However in SyncTo, there is this subtle condition that proves that it can actually happen when the Sync server returns no record : https://github.com/mozilla-services/syncto/blob/master/syncto/views/collection.py#L80-L81

This is thus a SyncTo server bug ! Good catch @ferjm !

**Comment by n1k0** [comment]
> This is thus a SyncTo server bug

Hence closing, thanks.

**Pull request closed without merging**
