### PR TITLE
Update SRIs for 4.0.0

### PR DESCRIPTION
**Pull request by glasserc**
r? @leplatrem

### CODE REVIEW

**Comment by leplatrem** [comment]
Strange I don't have the same checksums:

```
$ git checkout -b glasserc-update-sri master
$ git pull https://github.com/glasserc/kinto.js.git update-sri
$ npm install
$ npm run dist
$ npm run compute-sri

| kinto.js                | sha384-j4179fq3YFzqJA4KfeTJNTD9yxm7M93iX2s7yLK1fB8WENMkapTqScrbLJtD8aDD |
| kinto.min.js            | sha384-MffERZnHoxnymkXEIZi4+4q9faisvNWqw5EWdZwjI7KwS/FSekiChN3JW5/Geh5i |
| kinto.noshim.js         | sha384-81C02ftzQscqPHDOvDTzdeob96dl7QnaOTUnPlbIkTabAzrSZOpgqfNvWbyTHF35 |

```

**Comment by glasserc** [comment]
Maybe I'm running different versions of the dependencies. Let me `npm install` and try again...

**Comment by leplatrem** [comment]
I deleted my `node_modules` folder and reinstalled everything. Got : 
```
| kinto.js                | sha384-MUdIR7pARxZVGjSznOFL4DwubWEYfRb//ChmClWFQs5TQpO52dOjRp5sHL7LhMRN |
| kinto.min.js            | sha384-oD6TRIV81DdYa2vMFKVn8Ab/KcsPBqdzU1QU/WYS2SnSBaOpVu6sEvzadDhmSbV3 |
| kinto.noshim.js         | sha384-WsybVn+TjOrX0IcyUL5aEBgTKMs1nq2hrI1+OE1nB9aQRcRIOEVI8MIyyhwlRR7z |
```

with : 
```
$ node --version
v6.3.0

$ npm --version
3.10.3
```

**Comment by glasserc** [comment]
I did the release wrong, so I'm going to cut 4.0.1.

**Pull request closed without merging**
