### PR TITLE
Fix safari issue on IDB cursor with empty values

### LINKED ISSUE #524: Safari only DataError: DOM IDBDatabase Exception 0: The data provided does not meet requirements
screen shot 2016-08-23 at 12 32 19 pm

### PR DESCRIPTION
**Pull request by magopian**
Fixes #524

### CODE REVIEW

**Comment by leplatrem** [comment]
Another way to fix it ?

```diff
diff --git a/src/adapters/IDB.js b/src/adapters/IDB.js
index f96fc40..1927065 100644
--- a/src/adapters/IDB.js
+++ b/src/adapters/IDB.js
@@ -27,6 +27,9 @@ const cursorHandlers = {
   },
 
   in(values, done) {
+    if (values.length === 0) {
+      return done([]);
+    }
     const sortedValues = [].slice.call(values).sort();
     const results = [];
     return function(event) {
```

**Comment by magopian** [comment]
Works perfectly! I updated the PR

**Comment by leplatrem** [comment]
Cool, let's wait for green tests

**Comment by aegaas** [comment]
Sweet! We'll test this out today in our project. Is this going into 3.x and 4.x?

**Comment by aegaas** [comment]
Happy to report once we got the git#master version working in our app it was working great. However, it was kind of a pain to get working this way becayse src is in .npmignore and this makes it very difficult to build from npm.

**Comment by leplatrem** [comment]
I'll do my best to take some time to release some bug fix versions

**Comment by leplatrem** [comment]
Just backported and released v4.0.5, let me know if you need version 3.X too

**Pull request merged**
