### PR TITLE
Adds esdoc support.

### PR DESCRIPTION
**Pull request by n1k0**
Reviewing instructions:

- checkout this branch
- `npm install`
- `esdoc -c esdoc.json`
- `open esdoc/index.html`

Once this is merged, we'll host the generated esdocs on https://doc.esdoc.org/.

### CODE REVIEW

**Comment by n1k0** [comment]
r=? @leplatrem

**Comment by leplatrem** [comment]
Awright, so I guess this is not supposed to replace the narrative documentation...

* I guess that's part of your plan... I would suggest a link to this reference on the narrative docs (e.g. *See full API reference* or whatever)
* Coverage is 100%. I believe it's a good news :)
* I like the tests being documented, bringing a sort of spec in the docs ! \o/
* I would have like the functions to be listed under a `utils` module

capture d ecran de 2015-10-06 13 08 38

**Comment by leplatrem** [comment]
capture d ecran de 2015-10-06 13 09 33

If I'm not mistaken, this import does not work when using the package published on NPM  :(

**Comment by n1k0** [comment]
> I guess that's part of your plan... I would suggest a link to this reference on the narrative docs (e.g. See full API reference or whatever)

Yeah, this is definitely not aimed at replacing existing docs, just complementing them with more details. I'll add links to the regular api docs indeed.

> I would have like the functions to be listed under a `utils` module

I agree, though this doesn't seem to be supported by esdoc except if I move the `utils` module into its own subfolder, like for `adapters`… Strange to say the least, and I can't really justify adapting our file structure to adapt to this very limitation.

> If I'm not mistaken, this import does not work when using the package published on NPM :(

These are generated, and I can't modify that. There may be some option to add when packaging so babel users may just import whatever they need… Filed #193 about this.

**Comment by leplatrem** [comment]
Herr Plüs.

**Comment by h13i32maru** [comment]
Hi Kinto Team!
I am developing ESDoc. Thanks for using it.

> If I'm not mistaken, this import does not work when using the package published on NPM :(

[ESDoc Import Path Plugin](https://github.com/esdoc/esdoc-importpath-plugin) may resolve this problem.

> Yeah, this is definitely not aimed at replacing existing docs, just complementing them with more details. 

[ESDoc can integrate manual](https://esdoc.org/feature.html#integration-manual) may be helpful for Kinto Team.

Feel free this proposal. Thanks.

**Pull request merged**
