### PR TITLE
[WiP] Use bucket in demo

### PR DESCRIPTION
**Pull request by michielbdejong**
Haven't tested this yet.

### CODE REVIEW

**Comment by n1k0** [comment]
Could you explain the rationale behind this change? Demo users are all sharing the same auth credentials on purpose...

**Comment by michielbdejong** [comment]
It's just about best practices. We're pretty sure now that all known problems with the default bucket have been fixed, and so both systems (default bucket or one bucket per user) should work correctly now. But in case there are unknown unknowns there, keeping buckets separate feels like a nice extra safety measure that doesn't cost the developer anything, right?

**Comment by Natim** [comment]
> keeping buckets separate feels like a nice extra safety measure that doesn't cost the developer anything

Not exactly because the default bucket implicitely creates collections when first use which is not the case with other buckets.

**Comment by n1k0** [comment]
Because of implicit default bucket creation, we cannot simply specify a custom bucket that way; a better approach would probably be to properly document the procedure when one's willing to use custom buckets (with explicit creation operations).

**Comment by Natim** [comment]
The steps are:

```
    const createBucket = (server, bucketId, collectionId, authorization) => {
       return fetch(`${server}buckets/${bucketId}`, {
         method: 'PUT',
         headers: {
           Authorization: authorization
         }
       }).then(() => fetch(`${server}buckets/${bucketId}/collections/${collectionId}`, {
         method: 'PUT',
         headers: {
           Authorization: authorization
         }
       }));
    };
```

**Comment by michielbdejong** [comment]
ok!

**Pull request closed without merging**
