### PR TITLE
Add generator runtime for async/await

### PR DESCRIPTION
**Pull request by leplatrem**
After #548, running the demo fails with `ReferenceError: regeneratorRuntime is not defined`

I added the necessary Babel stuff. But this makes the build bigger :/

Before:

```
-rw-rw-r--  1 mathieu mathieu 1,2M sep 16 11:01 kinto.js
-rw-rw-r--  1 mathieu mathieu 250K sep 16 11:01 kinto.min.js
-rw-rw-r--  1 mathieu mathieu  86K sep 16 11:01 kinto.noshim.js
-rw-rw-r--  1 mathieu mathieu  88K sep 16 11:01 moz-kinto-offline-client.js
```

After:

```
-rw-rw-r--  1 mathieu mathieu 1,3M sep 16 11:04 kinto.js
-rw-rw-r--  1 mathieu mathieu 286K sep 16 11:04 kinto.min.js
-rw-rw-r--  1 mathieu mathieu 147K sep 16 11:04 kinto.noshim.js
-rw-rw-r--  1 mathieu mathieu 138K sep 16 11:04 moz-kinto-offline-client.js
```

What do think ?

Personnally, I think that having async/await in the codebase really helps understand the flow, and will really help us to refactor stuff. I'm ready ready to accept a bigger dist output...

I also think we have to put some more efforts to tweak the `noshim` and `moz-*` builds.

### CODE REVIEW

**Comment by n1k0** [comment]
And it's somewhat of a temporary situation as browsers will all eventually implement async/await anyway.

r+

**Comment by n1k0** [comment]
> I also think we have to put some more efforts to tweak the noshim and moz-* builds.

The noshim code should reflect its name and shouldn't provide any polyfills for await/async methinks.

For the moz build, propgress is regularly made on https://bugzilla.mozilla.org/show_bug.cgi?id=1185106 so one more time, shipping polyfills here is much likely to be an acceptably temporary solution.

**Comment by leplatrem** [comment]
> The noshim code should reflect its name and shouldn't provide any polyfills for await/async methinks.

I think so too, but I can get uglify working with such output :/

**Comment by n1k0** [comment]
> I think so too, but I can get uglify working with such output :/

Maybe we shouldn't uglify it? I feel like the noshim version wants to be legible...

**Comment by aegaas** [comment]
oh man, we could have used this in 4.0.5 since we're building for the browser

**Pull request merged**
