### PR TITLE
Kinto-client was renamed as kinto-http.js

### PR DESCRIPTION
**Pull request by ipsha21**

### CODE REVIEW

**Comment by n1k0** [comment]
Ah, thanks! While you're on it, could you please update all kinto-client references in the docs folder as well? Thank you :)

**Comment by ipsha21** [comment]
Updated

**Comment by n1k0** [comment]
We now have to wait for https://github.com/Kinto/kinto-http.js/pull/102 to land :) /cc @Natim

**Comment by Natim** [comment]
This PR doesn't change the code that uses kinto-client, it is still using kinto-client. We can merge it and then update the dependency as soon as Kinto/kinto-http.js#102 land.

**Comment by n1k0** [comment]
This will update docs with mentions of a not yet published package, but whatever.

**Comment by Natim** [comment]
So do you want to update the code as well and wait for the kinto-http.js PR to takes place?

**Comment by Natim** [comment]
Great @ipsha21 thanks.

**Pull request merged**
