### PR TITLE
Backported fix for babel-polyfill from 1.2.2.

### PR DESCRIPTION
**Pull request by n1k0**
This is a backport of #379 and #380 (landed on 1.2.2) to master.

r=? @leplatrem

### CODE REVIEW

**Comment by leplatrem** [comment]
No change to `build-noshim` ?

**Comment by n1k0** [comment]
> No change to build-noshim ?

Somehow I missed it. Will fix.

**Comment by n1k0** [comment]
Actually it appears that master was already ignoring `babel-polyfill` for noshim hence why it didn't conflict.

r=?

**Comment by n1k0** [comment]
I'm also decreasing failure treshold for coverage because here it fails because we're not covering the babel-polyfill if statement which is definitely too much.

**Comment by n1k0** [comment]
Note: I'm also removing the CHANGELOG.md file as I did for 1.2.2. We're moving to document this on Github release notes instead.

**Comment by leplatrem** [comment]
r+

**Pull request merged**
