### PR TITLE
Fix db transactions on safari.

### PR DESCRIPTION
**Pull request by QuentinRoy**
On Safari 8.0.8 (and priors, most likely), calling IDBDatabase.transaction with mode == undefined raises a TypeError (the browser won't use default mode value).
As a workaround, if mode is undefined, create the transaction without the mode argument.

### CODE REVIEW

**Comment by n1k0** [comment]
Thanks. I'm suspicious about the amount of changes for dist files:

screen shot 2015-08-26 at 16 15 16

How did you generate them?

**Comment by QuentinRoy** [comment]
Yes, I was surprised too.
I just run `npm build` and `npm dist`.

**Comment by QuentinRoy** [comment]
I believe it is because of changes in the compilers. Probably babel. If we want to avoid that, we may consider removing the `^` before the dependencies' versions in `package.json` so that the exact same dependencies are installed instead of the most recent compatible ones.

**Comment by n1k0** [comment]
> I believe it is caused by changes in the compilers

Could you please ensure that's the case, eg. sequentially using two distinct versions? I'm super surprised a new compiler version suddenly adds +50% generated code to the builds…

**Comment by QuentinRoy** [comment]
OK it is not be because of the compilers. Here is what I investigated:
* I tried to use the exact versions provided in the package.json and it gave me the same compiled file than with the more recent versions.
* I checked out the previous commit (c5f55f0) and compiled (using once again the compiler versions of package.son) and it gave me a very different result from what was in the commit.

I have no explanation.

**Comment by n1k0** [comment]
Superseded by #142.

**Pull request closed without merging**
