### PR TITLE
Fixes #215: Added internal links to esdoc.

### LINKED ISSUE #215: Investigate how to link to foreign symbols from within esdoc
Something like this:

```
/**
 * A link to {#sync()}
 */
```

### PR DESCRIPTION
**Pull request by n1k0**
r=? @leplatrem

### CODE REVIEW

**Comment by Natim** [comment]
lgtm.

**Comment by leplatrem** [comment]
We don't want them in the narrative docs ? `#justWondering`

r+ !

**Comment by n1k0** [comment]
> We don't want them in the narrative docs ?

What do you mean, [these](http://kintojs.readthedocs.org/en/latest/)? Public symbols are already linked to the API docs there, already.

**Comment by n1k0** [comment]
Note that if we move to host the narrative docs to esdoc, I suspect we'll be able to leverage their link syntax directly.

**Comment by n1k0** [comment]
I'm gonna land this.

**Pull request merged**
