### PR TITLE
Use IndexedDB by default in collection (fixes #345)

### LINKED ISSUE #345: Creating a collection without adapter throws a `No adapter provided` exception
```es6
import Collection, from "../src/collection";

new Collection(TEST_BUCKET_NAME, TEST_COLLECTION_NAME, api, {hooks});
```
throws a  `No adapter provided` exception

### PR DESCRIPTION
**Pull request by leplatrem**
@almet r?

### CODE REVIEW

**Comment by leplatrem** [comment]
Hum I realize that this should also|only apply to `new Kinto()`

**Comment by n1k0** [comment]
I don't get the use case we're trying to address here; care to elaborate?

**Comment by leplatrem** [comment]
@n1k0 see original issue by @almet : he instantiates a collection object https://github.com/Kinto/kinto.js/issues/345#issue-135728325

(We can also close this PR and the issue if irrelevant)

**Comment by n1k0** [comment]
> @n1k0 see original issue by @almet : he instantiates a collection object #345 (comment)

Ah, I never really expected people to instantiate Collection directly, but as it's part of the documented public API, it probably makes sense.

r+

**Pull request merged**
