### PR TITLE
Prepare 1.0.0-rc.1

### PR DESCRIPTION
**Pull request by n1k0**
#### Pre PR merge

- [x] Check dist files
- [x] Check package.json info
- [x] Check outdated deps
- [x] Add `CHANGELOG.md`

#### Post PR merge

- [ ] Create tag
- [ ] Publish to npm
- [ ] Create Github release with changelog
- [ ] Publish updated demo

### CODE REVIEW

**Comment by Natim** [comment]
We should release 1.0.0 instead of 0.6.0 because we are now supporting Kinto 1.x branch with this version of Kinto.js

Please file a 1.0.0.rc1 if you think this version is not good enough to have a 1.0.0 but I personally think that we can release 1.0.0 and release a 1.1.0 next if necessary.

**Comment by Natim** [comment]
We should probably add a CHANGELOG such as https://github.com/Kinto/kinto/blob/master/CHANGELOG.rst

**Comment by n1k0** [comment]
> We should release 1.0.0 instead of 0.6.0 because we are now supporting Kinto 1.x branch with this version of Kinto.js

0.6.0 is just another name for rc1 and is simpler to manage as a version name than *-rc1 with npm. Think of it as an intermediate version, I could just tag 1.0.0 tomorrow if needed.

**Comment by Natim** [comment]
The important thing for me is to have a meaningful major version of the semver (http://semver.org/) schema.

**Comment by n1k0** [comment]
Also, if possible (for now it is) I'd really like to stick with the [1.0.0 milestone](https://github.com/Kinto/kinto.js/milestones/1.0.0) scope for next major release.

**Comment by Natim** [comment]
Yes it was the reason why I was proposing that we sail 1.0.0 for now and 1.1.0 for the next milestone?

My overall goal was to give people a meaningful version number that gave information about the supported Kinto API. (v0 === 0. major version and v1 === 1. major version) but maybe you have strong arguments against this.

In any case passing from 0.2.0 to 0.6.0 and then to 1.0.0 doesn't soons right for me. We should either go from 0.2.0 to 0.3.0 or from 0.2.0 to 1.0.0

**Comment by n1k0** [comment]
I can probably investigate rc versionning using npm, though last time I checked it was a mess.

**Comment by n1k0** [comment]
Okay prereleases seems to be [well supported now](https://docs.npmjs.com/misc/semver#prerelease-tags).

**Pull request merged**
